apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2020-05-07T17:31:05Z"
  labels:
    app: apollo-backend
  name: apollo-backend
  namespace: development
  resourceVersion: "2034494"
  selfLink: /apis/build.openshift.io/v1/namespaces/development/buildconfigs/apollo-backend
  uid: 876bb216-9088-11ea-8022-0a580a800100
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: apollo-backend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/stephmen/ApolloBackend
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: PRISMA_ENDPOINT
        value: '"http://172.30.241.100:4466"'
      - name: PRISMA_SECRET
        value: '"prisma"'
      - name: APP_SECRET
        value: '"prisma"'
      - name: WHITELIST
        value: '["http://prisma-development.apps-crc.testing",  "prisma-development.apps-crc.testing",
          "http://172.25.206.52:4466", 172.30.52.150, "apollo-backend-development.apps-crc.testing",
          "http://apollo-backend-development.apps-crc.testing", 172.30.90.125, "frontend-development.apps-crc.testing",
          "http://frontend-development.apps-crc.testing", "http://checkout.stripe.com/"]'
      from:
        kind: ImageStreamTag
        name: nodejs:latest
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: qS64U9bwynToBFUGWNTw
    type: GitHub
  - generic:
      secret: l0aqQVI6nAdYNpdvOVPy
    type: Generic
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:74a3ef2964efc03dfc239da3f09691b720ce54ff4bb47588864adb222133f0fc
    type: ImageChange
status:
  lastVersion: 8
