apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yaml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    io.kompose.service: mongo
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: prisma
        - name: MONGO_INITDB_ROOT_USERNAME
          value: prisma
        image: ' '
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mongo
          name: mongo-production
        - mountPath: /data/db
          name: mongo-claim1--production
        - mountPath: /data/configdb
          name: mongo-claim2--production
      restartPolicy: Always
      volumes:
      - name: mongo-production
        persistentVolumeClaim:
          claimName: mongo-production
      - name: mongo-claim1-production
        persistentVolumeClaim:
          claimName: mongo-claim1-production
      - name: mongo-claim2-production
        persistentVolumeClaim:
          claimName: mongo-claim2-production
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - mongo
      from:
        kind: ImageStreamTag
        name: mongo:3.6
    type: ImageChange
status: {}
