apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yaml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: prisma
  name: prisma
spec:
  replicas: 1
  selector:
    io.kompose.service: prisma
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: prisma
    spec:
      containers:
      - env:
        - name: PRISMA_CONFIG
          value: |
            port: 4466
            databases:
              default:
                connector: mongo
                uri: mongodb://prisma:prisma@mongo
        image: ' '
        name: prisma
        ports:
        - containerPort: 4466
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - prisma
      from:
        kind: ImageStreamTag
        name: prisma:1.34
    type: ImageChange
status: {}
