apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: prisma
  name: prisma
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: prismagraphql/prisma:1.34
    generation: null
    importPolicy: {}
    name: "1.34"
status:
  dockerImageRepository: ""
