apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2020-05-07T17:18:32Z"
  labels:
    app: frontend
  name: frontend
  namespace: development
  resourceVersion: "1993591"
  selfLink: /api/v1/namespaces/development/services/frontend
  uid: c70abdec-9086-11ea-9ae3-0ef0e3c74fbe
spec:
  clusterIP: 172.30.90.125
  ports:
  - name: 7777-tcp
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app: frontend
    deploymentconfig: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
