apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-25T17:20:27Z"
  name: myapp
  namespace: production
  resourceVersion: "1201464"
  selfLink: /api/v1/namespaces/production/services/myapp
  uid: 0ec33f96-8719-11ea-b7a3-0ef0e3c74fbe
spec:
  clusterIP: 172.30.28.202
  ports:
  - port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    deployment-config.name: myapp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
